name: Happy Universe Man
favicon: null
layout_spectrum: 0.99076
typography_spectrum: 0.94954
title: Happy Universe Man
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#938d2d'
    - '#a3b2b5'
    - '#d2d9db'
    - '#cac89b'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
