typography_spectrum: 0.94954
color:
  brandColors:
    - '#ffffff'
    - '#938d2d'
    - '#a3b2b5'
    - '#d2d9db'
    - '#cac89b'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.75
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99076
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jasen
  email: web@happyuniverseman.com
  url: happyuniverseman.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/41943718-9080-4f19-b0b3-80ffc5b7ea4b.jpg
name: Happy Universe Man
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: 39ab3285-86e9-47c4-a645-5417ba91128c
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0fb119c5-80ea-42c1-b93a-011891a4f33f.jpg
title: Happy Universe Man
description: for a happy heart and a peaceful mind
purpose: []
