typography_spectrum: 0.94954
color:
  brandColors:
    - '#ffffff'
    - '#938d2d'
    - '#a3b2b5'
    - '#d2d9db'
    - '#cac89b'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.75
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99076
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jasen
  email: web@happyuniverseman.com
  url: happyuniverseman.com
name: Happy Universe Man
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Happy Universe Man
description: for a happy heart and a peaceful mind
purpose: []
