name: HappyUniverseMan
favicon: null
layout_spectrum: 0.994849982438609
typography_spectrum: 0.8962514316663146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.27517818030901253
  lightness: 0.5592549904249609
  saturation: 0.249749741749838
  rhythmicContrast: 0.6659302429761738
purpose: []
